name: Poll Telegram updates

on:
  schedule:
    - cron: '* * * * *'   # каждую минуту
  workflow_dispatch:

permissions:
  contents: write

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Restore last_update.txt from cache
        uses: actions/cache@v4
        with:
          path: last_update.txt
          key: last-update-cache
          restore-keys: |
            last-update-cache

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run bot script
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GETPLATINUM_API_KEY: ${{ secrets.GETPLATINUM_API_KEY }}
        run: python bot.py

      - name: Save last_update.txt to cache
        uses: actions/cache/save@v4
        with:
          path: last_update.txt
          key: last-update-cache-v3
